#!/bin/bash

# Check if we have node/npm installed
if ! [ -x "$(command -v npm)" ]; then
  echo "Could not find node/npm. Please install and re-run the script"
  exit 1
fi

# Check if we have meteor instaled, install if not
if ! [ -x "$(command -v meteor)" ]; then
  echo "Could not find meteor, installing"
  curl https://install.meteor.com/ | sh
  if ! [ $0 -eq 0 ]; then
    echo "Could not install meteor. Aborting..."
    exit 1
  fi
fi

echo "Running meteor build"
echo "Destination: ../build-output-rcchat"

meteor build --server-only ../build-output-rcchat

if ! [ $0 -eq 0 ]; then
  echo "Something went wrong while meteor build"
  exit 1
fi

cp ../build-output-rcchat ./build-output-rcchat

docker build --tag pp-rcchat-dev:v1 .
echo "Completed"
