#!/bin/bash

set -e

rm -f Rocket.Chat.tar.*
rm -fr ./build-output-rcchat

# Install imagemagick
sudo apt-get install -y imagemagick

# Check if we have node/npm installed
if ! [ -x "$(command -v npm)" ]; then
  echo "Could not find node/npm. Please install and re-run the script"
  exit 1
fi

# Check if we have meteor instaled, install if not
if ! [ -x "$(command -v meteor)" ]; then
  echo "Could not find meteor, installing"
  curl https://install.meteor.com/ | sh  
fi

echo "Running npm install"
npm install sharp
npm install

echo "Running meteor build"
echo "Destination: ../build-output-rcchat"

export TOOL_NODE_FLAGS="--max-old-space-size=4096 --optimize_for_size --gc-interval=100"
echo $TOOL_NODE_FLAGS

meteor build --server-only ./build-output-rcchat

cp -R ./build-output-rcchat/Rocket.Chat.tar.gz ./

docker build --tag pp-rcchat-dev:v1 .
echo "Completed"
