#!/bin/bash

ETCD_HOST = "https://rnd-etcd01.rnd.projectplace.com:2379"
CONFIG_DATA = "dev/in/nix"

TEMPFILE=$(mktemp)

function cleanup {
    rm $TEMPFILE
}

trap cleanup EXIT

function gen_cfg {
  local config destination
  config=$1
  template=$2
  destination=$3
  export TMPFILE=$(mktemp /tmp/mkconf.$$.XXXXX)
  trap "rm -f $TMPFILE" EXIT ERR

  cd /opt/src/config
  if ! /opt/python-pp/bin/python etcd_render $ETCD_HOST $config $template > $TMPFILE; then
    echo "WARNING: failed to generate config $destination"
    exit 1
  fi
  cp -f $TMPFILE $destination
  chmod +r $destination
  rm -f $TMPFILE
}

gen_cfg /rc_config_data/$CONFIG_DATA /app/config/v110.js.jinja2 /app/config/v110.js
