#!/bin/bash

# Currently hard coded path. Will change later
ETCD_HOST="https://rnd-etcd01.rnd.projectplace.com:2379"
MONGO_SERVER_CONFIG_PATH='/pp_config_data/dev/in'
PP_CHAT_CONFIG_PATH='/pp_config_data/dev/in/nix/sdatta'

TEMPFILE=$(mktemp)

function cleanup {
    rm $TEMPFILE
}

trap cleanup EXIT

function gen_cfg {
  local config destination
  config=$1
  template=$2
  destination=$3
  export TMPFILE=$(mktemp /tmp/mkconf.$$.XXXXX)
  trap "rm -f $TMPFILE" EXIT ERR

  cd /app/config
  if ! python etcd_render $ETCD_HOST $config $template > $TMPFILE; then
    echo "WARNING: failed to generate config $destination"
    exit 1
  fi
  cp -f $TMPFILE $destination
  chmod +r $destination
  rm -f $TMPFILE
}

